# Generated by Django 4.0.4 on 2022-04-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Dates',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('transaction_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('origin_bank', models.CharField(max_length=100)),
                ('origin_agency', models.CharField(max_length=10)),
                ('origin_account', models.CharField(max_length=10)),
                ('destiny_bank', models.CharField(max_length=100)),
                ('destiny_agency', models.CharField(max_length=10)),
                ('destiny_account', models.CharField(max_length=10)),
                ('value_transaction', models.FloatField(max_length=100)),
                ('transaction_date', models.DateTimeField()),
            ],
        ),
    ]
