# Generated by Django 4.0.4 on 2022-04-19 11:58

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alurafiles', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dates',
        ),
        migrations.AddField(
            model_name='transactions',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
