# Generated by Django 4.0.4 on 2022-04-19 12:04

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alurafiles', '0002_delete_dates_transactions_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='created_at',
            field=models.DateField(default=datetime.date(2022, 4, 19)),
        ),
    ]
