# Generated by Django 4.0.4 on 2022-04-19 13:20

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alurafiles', '0003_alter_transactions_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2022, 4, 19)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateField(),
        ),
    ]
