# Generated by Django 4.0.4 on 2022-04-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alurafiles', '0004_alter_transactions_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
