# Generated by Django 4.0.4 on 2022-04-28 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alurafiles', '0008_dates_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='value_transaction',
            field=models.BigIntegerField(),
        ),
    ]
