# Generated by Django 4.0.4 on 2022-04-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alurafiles', '0009_alter_transactions_value_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='transaction_date',
            field=models.DateField(max_length=255),
        ),
    ]
